version: '3'

services:
  app:
    image: ${PREFIX}_${APP_CONTAINER_NAME}:latest
    container_name: ${PREFIX}_${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    ports:
      - ${APP_PUBLIC_PORT}:8000

    env_file:
      - .env

    volumes:
      - .:/usr/src/app/
      - ${ROOT_VOLUME_DIR}/static_volume:/home/app/staticfiles
      - ${ROOT_VOLUME_DIR}/media_volume:/home/app/mediafiles

    depends_on:
      - mariadb
    restart: always

  app_celery:
    container_name: ${PREFIX}_${APP_CONTAINER_NAME}_celery
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    image: ${PREFIX}_${APP_CONTAINER_NAME}:latest
    command: celery -A diana worker --loglevel=info

    env_file:
      - .env

    volumes:
      - .:/usr/src/app/
      - ${ROOT_VOLUME_DIR}/static_volume:/home/app/staticfiles
      - ${ROOT_VOLUME_DIR}/media_volume:/home/app/mediafiles

    depends_on:
      - mariadb
      - app
    restart: always

  app_celery_beat:
    container_name: ${PREFIX}_${APP_CONTAINER_NAME}_celery_beat
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    image: ${PREFIX}_${APP_CONTAINER_NAME}:latest
    command: celery -A diana beat -l info -S django
    env_file:
      - .env

    volumes:
      - .:/usr/src/app/
      - ${ROOT_VOLUME_DIR}/static_volume:/home/app/staticfiles
      - ${ROOT_VOLUME_DIR}/media_volume:/home/app/mediafiles

    depends_on:
      - mariadb
      - app

    restart: always

  mariadb:
    image: mariadb:10.6.5-focal
    container_name: ${PREFIX}_${MARIADB_CONTAINER_NAME}
    ports:
      - ${MARIADB_PUBLIC_PORT}:${MARIADB_PORT}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      # Auto Create DB
      MYSQL_DATABASE: ${MARIADB_DATABASE}

    volumes:
      - ${ROOT_VOLUME_DIR}/mariadb_volume/data:/var/lib/mysql
      - ${ROOT_VOLUME_DIR}/mariadb_volume/scripts:/var/www/scripts # Run: source /var/www/scripts/xxx.sql to import db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    container_name: ${PREFIX}_${PHPMYADMIN_CONTAINER_NAME}

    environment:
      PMA_HOST: mariadb
      # PMA_PORT: ${MARIADB_PORT}
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
      # MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    restart: always
    ports:
      - ${PHPMYADMIN_PUBLIC_PORT}:80
    depends_on:
      - mariadb

  redis:
    image: redis:6.2.6
    container_name: ${PREFIX}_${REDIS_CONTAINER_NAME}
    restart: always
  

